### ISSUE TITLE
能否支持动态生成输出 (Can support dynamically generated output)

### ISSUE THREAD

**Issue by sxin0** [dolanmiu/docsify-terminal-block#2]
类似这种效果 (similar to this effect)
https://fastapi.tiangolo.com/zh/#_6
![image](https://github.com/dolanmiu/docsify-terminal-block/assets/29392026/d865cf95-b3dc-4918-afb9-a4f16b71757d)

**Comment by dolanmiu** [comment]
不可能不。 只有静态 (Not possible, only static)
